-- Wedding Hall (To'yxona) Booking System — idempotent DDL

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE user_role AS ENUM ('ADMIN','OWNER','CUSTOMER');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'district_enum') THEN
    CREATE TYPE district_enum AS ENUM (
      'Chilanzar','Yunusabad','Mirabad','Yakkasaray','Shaykhantahur','Almazar',
      'Mirzo_Ulugbek','Uchtepa','Sergeli','Bektemir','Yashnabad','Yangihayot'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'hall_status') THEN
    CREATE TYPE hall_status AS ENUM ('PENDING','APPROVED');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'booking_status') THEN
    CREATE TYPE booking_status AS ENUM ('UPCOMING','COMPLETED','CANCELLED');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'service_type') THEN
    CREATE TYPE service_type AS ENUM ('SINGER','CAR','KARNAY_SURNAY');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS users (
  id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name      VARCHAR(100) NOT NULL,
  last_name       VARCHAR(100) NOT NULL,
  phone_number    VARCHAR(20)  NOT NULL,
  email           VARCHAR(150) NOT NULL UNIQUE,
  username        VARCHAR(50)  NOT NULL UNIQUE,
  password_hash   VARCHAR(255) NOT NULL,
  role            user_role    NOT NULL DEFAULT 'CUSTOMER',
  is_verified     BOOLEAN      NOT NULL DEFAULT FALSE,
  otp_code        VARCHAR(6)   NULL,
  created_at      TIMESTAMP    NOT NULL DEFAULT now()
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_expires_at TIMESTAMP NULL;

CREATE TABLE IF NOT EXISTS wedding_halls (
  id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id            INT           NOT NULL,
  name                VARCHAR(255)  NOT NULL,
  district            district_enum NOT NULL,
  address             TEXT          NOT NULL,
  capacity            INT           NOT NULL,
  price_per_seat      DECIMAL(12,2) NOT NULL,
  phone_number        VARCHAR(20)   NOT NULL,
  status              hall_status   NOT NULL DEFAULT 'PENDING',
  has_karnay_surnay   BOOLEAN       NOT NULL DEFAULT FALSE,
  karnay_surnay_price DECIMAL(12,2) NULL,
  created_at          TIMESTAMP     NOT NULL DEFAULT now(),

  CONSTRAINT fk_wedding_halls_owner
    FOREIGN KEY (owner_id)
    REFERENCES users(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT chk_wedding_halls_capacity
    CHECK (capacity > 0),

  CONSTRAINT chk_wedding_halls_price_per_seat
    CHECK (price_per_seat >= 0),

  CONSTRAINT chk_wedding_halls_karnay_price_nonneg
    CHECK (karnay_surnay_price IS NULL OR karnay_surnay_price >= 0),

  CONSTRAINT chk_karnay_surnay_price
    CHECK (
      (has_karnay_surnay = TRUE AND karnay_surnay_price IS NOT NULL)
      OR
      (has_karnay_surnay = FALSE)
    )
);

CREATE TABLE IF NOT EXISTS hall_images (
  id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hall_id   INT  NOT NULL,
  image_url TEXT NOT NULL,

  CONSTRAINT fk_hall_images_hall
    FOREIGN KEY (hall_id)
    REFERENCES wedding_halls(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS singers (
  id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hall_id   INT           NOT NULL,
  name      VARCHAR(255)  NOT NULL,
  price     DECIMAL(12,2) NOT NULL,
  image_url TEXT          NULL,

  CONSTRAINT fk_singers_hall
    FOREIGN KEY (hall_id)
    REFERENCES wedding_halls(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

  CONSTRAINT chk_singers_price
    CHECK (price >= 0)
);

CREATE TABLE IF NOT EXISTS cars (
  id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hall_id   INT           NOT NULL,
  brand     VARCHAR(255)  NOT NULL,
  price     DECIMAL(12,2) NOT NULL,
  image_url TEXT          NULL,

  CONSTRAINT fk_cars_hall
    FOREIGN KEY (hall_id)
    REFERENCES wedding_halls(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

  CONSTRAINT chk_cars_price
    CHECK (price >= 0)
);

CREATE TABLE IF NOT EXISTS menus (
  id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hall_id   INT          NOT NULL,
  name      VARCHAR(255) NOT NULL,
  image_url TEXT         NULL,

  CONSTRAINT fk_menus_hall
    FOREIGN KEY (hall_id)
    REFERENCES wedding_halls(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  INT           NOT NULL,
  hall_id      INT           NOT NULL,
  booking_date DATE          NOT NULL,
  guest_count  INT           NOT NULL,
  total_price  DECIMAL(12,2) NOT NULL,
  deposit_paid DECIMAL(12,2) NOT NULL,
  status       booking_status NOT NULL DEFAULT 'UPCOMING',
  created_at   TIMESTAMP     NOT NULL DEFAULT now(),

  CONSTRAINT fk_bookings_customer
    FOREIGN KEY (customer_id)
    REFERENCES users(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT fk_bookings_hall
    FOREIGN KEY (hall_id)
    REFERENCES wedding_halls(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT chk_bookings_guest_count
    CHECK (guest_count > 0),

  CONSTRAINT chk_bookings_total_price
    CHECK (total_price >= 0),

  CONSTRAINT chk_bookings_deposit_paid
    CHECK (deposit_paid >= 0)
);

CREATE TABLE IF NOT EXISTS booking_services (
  id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id      INT           NOT NULL,
  service_type    service_type  NOT NULL,
  service_item_id INT           NULL,
  price           DECIMAL(12,2) NOT NULL,

  CONSTRAINT fk_booking_services_booking
    FOREIGN KEY (booking_id)
    REFERENCES bookings(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

  CONSTRAINT chk_booking_services_price
    CHECK (price >= 0),

  CONSTRAINT chk_booking_services_item
    CHECK (
      (service_type IN ('SINGER','CAR') AND service_item_id IS NOT NULL)
      OR
      (service_type = 'KARNAY_SURNAY' AND service_item_id IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_wedding_halls_owner_id ON wedding_halls(owner_id);
CREATE INDEX IF NOT EXISTS idx_hall_images_hall_id    ON hall_images(hall_id);
CREATE INDEX IF NOT EXISTS idx_singers_hall_id        ON singers(hall_id);
CREATE INDEX IF NOT EXISTS idx_cars_hall_id           ON cars(hall_id);
CREATE INDEX IF NOT EXISTS idx_menus_hall_id          ON menus(hall_id);
CREATE INDEX IF NOT EXISTS idx_bookings_customer_id   ON bookings(customer_id);
CREATE INDEX IF NOT EXISTS idx_bookings_hall_id       ON bookings(hall_id);
CREATE INDEX IF NOT EXISTS idx_booking_services_booking_id ON booking_services(booking_id);
CREATE INDEX IF NOT EXISTS idx_booking_services_type_item  ON booking_services(service_type, service_item_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_active_bookings_hall_date
ON bookings(hall_id, booking_date)
WHERE status IN ('UPCOMING','COMPLETED');
