// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig } from 'prisma/config'

// Tizimda DATABASE_URL borligini tekshiramiz, agar yo'q bo'lsa build paytida aniq xato berishi uchun
const databaseUrl = process.env['DATABASE_URL']
if (!databaseUrl) {
	throw new Error('DATABASE_URL is not defined in environment variables')
}

export default defineConfig({
	schema: 'prisma/schema.prisma',
	migrations: {
		path: 'prisma/migrations',
	},
	datasource: {
		url: databaseUrl, // Endi bu yerda undefined bo'lishi imkonsiz, faqat string bor
	},
})
